linters:
  enable:
    - bidichk
    - bodyclose
    - cyclop
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - funlen
    - gci
    - gocognit
    - goconst
    - gocyclo
    - gofmt
    - gofumpt
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacebloat
    - lll
    - maintidx
    - nestif
    - prealloc
    - predeclared
    - promlinter
    - revive
    - tagliatelle
    - typecheck
    - thelper
    - unconvert
    - unused

run:
  go: "1.19"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - maintidx
        - gochecknoglobals
        - lll

linters-settings:
  stylecheck:
    checks: ["all"]
